@startumlskinparam linetype orthoclass PtaiIssueDescription {  string identity  Dictionary<Category, List<string>> categories}enum IssueType {  VULNERABILITY,   WEAKNESS,   SCA,   CONFIGURATION,   BLACKBOX,   YARAMATCH,   UNKNOWN}PtaiIssueDescription -up-> IssueType : typeenum Level{  NONE, POTENTIAL, LOW, MEDIUM, HIGH}PtaiIssueDescription -up-> Level : levelenum Category {   CWE,   NIST,   OWASP,   PCIDSS }PtaiIssueDescription::categories ..> Categoryenum Language{  PHP,   JAVA,   CSHARP,   VB,   JS,   GO,   CPP,   PYTHON,   SQL,   OBJECTIVEC,   SWIFT,   KOTLIN}PtaiIssueDescription -down-> "*" Language : languagesenum Locale{  EN = 1033,  RU = 1049}PtaiIssueDescription .left.> Localeclass I18n{  string header  string description}PtaiIssueDescription --> "Locale" I18n : values[]I18n --> Html : htmlclass Html{  Boolean zipped  string data}        @enduml