@startumlskinparam linetype orthoclass PtaiIssueDescription {  string identity}enum Category {   CWE,   NIST,   OWASP,   PCIDSS }class Stringenum Locale{  EN = 1033,  RU = 1049}PtaiIssueDescription -> "1..*" String : categories(PtaiIssueDescription, String) .. Categoryenum IssueType {  VULNERABILITY,   WEAKNESS,   SCA,   CONFIGURATION,   BLACKBOX,   YARAMATCH,   UNKNOWN}PtaiIssueDescription -up-> IssueType : typeenum Level{  NONE, POTENTIAL, LOW, MEDIUM, HIGH}PtaiIssueDescription -up-> Level : levelenum Language{  PHP,   JAVA,   CSHARP,   VB,   JS,   GO,   CPP,   PYTHON,   SQL,   OBJECTIVEC,   SWIFT,   KOTLIN}PtaiIssueDescription -up-> "*" Language : languagesclass I18n{  string header  string description}PtaiIssueDescription --> "1..*" I18n : values(PtaiIssueDescription, I18n) .. LocaleI18n --> Html : htmlclass Html{  Boolean zipped  string data}        @enduml